export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODCUCT_LIST_SUCCESS = "PRODCUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODCUCT_DETAILS_SUCCESS = "PRODCUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
